### ISSUE TITLE
Make an option to hide all usernames

### ISSUE THREAD

**Issue by LoadingScreen** [ForumMagnum/ForumMagnum#45] opened 2017-07-09 00:53 UTC
I notice that my evaluation of a claim is strongly affected by who says it.
I would like it if I couldn't see anyone's username unless I clicked a "reveal username" button.

┆Issue is synchronized with this [Trello card](https://trello.com/c/9isknmnO) by [Unito](https://www.unito.io/learn-more)

**Comment by jimrandomh** [comment] 2022-10-20 19:55
Duplicate of #5910 (newer, now done)

**Closed by jimrandomh** 2022-10-20 19:55 UTC
Labels: 7. Feature, 3. Low Priority (Hard)
