### ISSUE TITLE
Simple bug on the shortform submission 

### ISSUE THREAD

**Issue by Huge** [ForumMagnum/ForumMagnum#5931] opened 2022-10-24 08:36 UTC
Replicate: Go to https://www.lesswrong.com/shortform , type your text, move to the middle of your line eg.
"abc ^{cursor here} is my fav sequence." , press Cmd+Enter on a MacOS, probably Ctrl+Enter will do the same on other desktops.

You will see "abc 
is my fav sequence."
is saved, which is a BUG.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1203225031101010) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment] 2022-10-25 20:35
Duplicate of #5045

**Closed by jpaddison3** 2022-10-25 20:35 UTC
