### ISSUE TITLE
Comment previews sometimes break markdown

### ISSUE THREAD

**Issue by david-mears-2** [ForumMagnum/ForumMagnum#7611] opened 2023-07-24 11:52 UTC
The comment preview should probably not show the raw markdown.

![Screenshot 2023-07-24 at 12 51 49](https://github.com/ForumMagnum/ForumMagnum/assets/60350599/5c8684d3-5eb8-421d-b75d-93a9310ce6ca)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205123235884192) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment] 2023-07-25 21:29
Closing as duplicate of: https://github.com/ForumMagnum/ForumMagnum/issues/7101

**Closed** 2023-07-25 21:29 UTC
